// Ghana's 16 regions and their district/municipal/metropolitan assemblies (MMDAs).
export const GHANA_REGIONS: Record<string, string[]> = {
  "Ahafo": [
    "Asunafo North Municipal",
    "Asunafo South District",
    "Asutifi North District",
    "Asutifi South District",
    "Tano North Municipal",
    "Tano South Municipal",
  ],
  "Ashanti": [
    "Adansi Asokwa District",
    "Adansi North District",
    "Adansi South District",
    "Afigya-Kwabre North District",
    "Afigya-Kwabre South District",
    "Ahafo-Ano North Municipal",
    "Ahafo-Ano South East District",
    "Ahafo-Ano South West District",
    "Akrofuom District",
    "Amansie Central District",
    "Amansie West District",
    "Amansie South District",
    "Asante-Akim Central Municipal",
    "Asante-Akim North District",
    "Asante-Akim South Municipal",
    "Asokore-Mampong Municipal",
    "Asokwa Municipal",
    "Atwima-Kwanwoma District",
    "Atwima-Mponua District",
    "Atwima-Nwabiagya Municipal",
    "Atwima-Nwabiagya North District",
    "Bekwai Municipal",
    "Bosome Freho District",
    "Bosomtwe District",
    "Ejisu Municipal",
    "Ejura/Sekyedumase Municipal",
    "Juaben Municipal",
    "Kumasi Metropolitan",
    "Kwabre East Municipal",
    "Kwadaso Municipal",
    "Mampong Municipal",
    "Obuasi East Municipal",
    "Obuasi Municipal",
    "Offinso Municipal",
    "Offinso North District",
    "Oforikrom Municipal",
    "Old Tafo Municipal",
    "Sekyere Afram Plains District",
    "Sekyere Central District",
    "Sekyere East District",
    "Sekyere Kumawu District",
    "Sekyere South District",
    "Suame Municipal",
  ],
  "Bono": [
    "Banda District",
    "Berekum East Municipal",
    "Berekum West District",
    "Dormaa Central Municipal",
    "Dormaa East District",
    "Dormaa West District",
    "Jaman North District",
    "Jaman South Municipal",
    "Sunyani Municipal",
    "Sunyani West District",
    "Tain District",
    "Wenchi Municipal",
  ],
  "Bono East": [
    "Atebubu-Amantin Municipal",
    "Kintampo North Municipal",
    "Kintampo South District",
    "Nkoranza North District",
    "Nkoranza South Municipal",
    "Pru East District",
    "Pru West District",
    "Sene East District",
    "Sene West District",
    "Techiman Municipal",
    "Techiman North District",
  ],
  "Central": [
    "Abura/Asebu/Kwamankese District",
    "Agona East District",
    "Agona West Municipal",
    "Ajumako/Enyan/Essiam District",
    "Asikuma Odoben Brakwa District",
    "Assin Central Municipal",
    "Assin North District",
    "Assin South District",
    "Awutu Senya East Municipal",
    "Awutu Senya West District",
    "Cape Coast Metropolitan",
    "Effutu Municipal",
    "Ekumfi District",
    "Gomoa East District",
    "Gomoa Central District",
    "Gomoa West District",
    "Komenda/Edina/Eguafo/Abirem Municipal",
    "Mfantsiman Municipal",
    "Twifo Atti Morkwa District",
    "Twifo/Hemang/Lower Denkyira District",
    "Upper Denkyira East Municipal",
    "Upper Denkyira West District",
  ],
  "Eastern": [
    "Abuakwa North Municipal",
    "Abuakwa South Municipal",
    "Achiase District",
    "Akuapim North Municipal",
    "Akuapim South District",
    "Akyemansa District",
    "Asene Manso Akroso District",
    "Asuogyaman District",
    "Atiwa East District",
    "Atiwa West District",
    "Ayensuano District",
    "Birim Central Municipal",
    "Birim North District",
    "Birim South District",
    "Denkyembour District",
    "Fanteakwa North District",
    "Fanteakwa South District",
    "Kwaebibirem Municipal",
    "Kwahu Afram Plains North District",
    "Kwahu Afram Plains South District",
    "Kwahu East District",
    "Kwahu South District",
    "Kwahu West Municipal",
    "Lower Manya Krobo Municipal",
    "New Juaben North Municipal",
    "New Juaben South Municipal",
    "Nsawam Adoagyire Municipal",
    "Okere District",
    "Suhum Municipal",
    "Upper Manya Krobo District",
    "Upper West Akim District",
    "West Akim Municipal",
    "Yilo-Krobo Municipal",
  ],
  "Greater Accra": [
    "Ablekuma Central Municipal",
    "Ablekuma North Municipal",
    "Ablekuma West Municipal",
    "Accra Metropolitan",
    "Ada East District",
    "Ada West District",
    "Adenta Municipal",
    "Ashaiman Municipal",
    "Ayawaso Central Municipal",
    "Ayawaso East Municipal",
    "Ayawaso North Municipal",
    "Ayawaso West Municipal",
    "Ga Central Municipal",
    "Ga East Municipal",
    "Ga North Municipal",
    "Ga South Municipal",
    "Ga West Municipal",
    "Korle-Klottey Municipal",
    "Kpone-Katamanso Municipal",
    "Krowor Municipal",
    "La-Dade-Kotopon Municipal",
    "La-Nkwantanang-Madina Municipal",
    "Ledzokuku Municipal",
    "Ningo-Prampram District",
    "Okaikwei North Municipal",
    "Shai-Osudoku District",
    "Tema Metropolitan",
    "Tema West Municipal",
    "Weija Gbawe Municipal",
  ],
  "Northern": [
    "Gushegu Municipal",
    "Karaga District",
    "Kpandai District",
    "Kumbungu District",
    "Mion District",
    "Nanton District",
    "Nanumba North Municipal",
    "Nanumba South District",
    "Saboba District",
    "Sagnarigu Municipal",
    "Savelugu Municipal",
    "Tamale Metropolitan",
    "Tatale Sanguli District",
    "Tolon District",
    "Yendi Municipal",
    "Zabzugu District",
  ],
  "North East": [
    "Bunkpurugu Nyankpanduri District",
    "Chereponi District",
    "East Mamprusi Municipal",
    "Mamprugu Moagduri District",
    "West Mamprusi Municipal",
    "Yunyoo-Nasuan District",
  ],
  "Oti": [
    "Biakoye District",
    "Guan District",
    "Jasikan Municipal",
    "Kadjebi District",
    "Krachi East Municipal",
    "Krachi Nchumuru District",
    "Krachi West Municipal",
    "Nkwanta North District",
    "Nkwanta South Municipal",
  ],
  "Savannah": [
    "Bole District",
    "Central Gonja District",
    "East Gonja Municipal",
    "North Gonja District",
    "North East Gonja District",
    "Sawla-Tuna-Kalba District",
    "West Gonja Municipal",
  ],
  "Upper East": [
    "Bawku Municipal",
    "Bawku West District",
    "Binduri District",
    "Bolgatanga East District",
    "Bolgatanga Municipal",
    "Bongo District",
    "Builsa North Municipal",
    "Builsa South District",
    "Garu District",
    "Kassena-Nankana Municipal",
    "Kassena-Nankana West District",
    "Nabdam District",
    "Pusiga District",
    "Talensi District",
    "Tempane District",
  ],
  "Upper West": [
    "Daffiama Bussie Issa District",
    "Jirapa Municipal",
    "Lambussie Karni District",
    "Lawra Municipal",
    "Nadowli-Kaleo District",
    "Nandom Municipal",
    "Sissala East Municipal",
    "Sissala West District",
    "Wa East District",
    "Wa Municipal",
    "Wa West District",
  ],
  "Volta": [
    "Adaklu District",
    "Afadzato South District",
    "Agotime Ziope District",
    "Akatsi North District",
    "Akatsi South District",
    "Anloga District",
    "Central Tongu District",
    "Ho Municipal",
    "Ho West District",
    "Hohoe Municipal",
    "Keta Municipal",
    "Ketu North Municipal",
    "Ketu South Municipal",
    "Kpando Municipal",
    "North Dayi District",
    "North Tongu District",
    "South Dayi District",
    "South Tongu District",
  ],
  "Western": [
    "Ahanta West Municipal",
    "Amenfi Central District",
    "Amenfi West Municipal",
    "Effia Kwesimintsim Municipal",
    "Ellembelle District",
    "Jomoro Municipal",
    "Mpohor District",
    "Nzema East Municipal",
    "Prestea-Huni Valley Municipal",
    "Sekondi Takoradi Metropolitan",
    "Shama District",
    "Tarkwa-Nsuaem Municipal",
    "Wassa Amenfi East Municipal",
    "Wassa East District",
  ],
  "Western North": [
    "Aowin Municipal",
    "Bia East District",
    "Bia West District",
    "Bibiani Anhwiaso Bekwai Municipal",
    "Bodi District",
    "Juaboso District",
    "Sefwi Akontombra District",
    "Sefwi-Wiawso Municipal",
    "Suaman District",
  ],
};

export const GHANA_REGION_NAMES = Object.keys(GHANA_REGIONS);
